name: demo_env
channels:
  - defaults
dependencies:
  - python=3.12.11
  - m2w64-toolchain=5.3.0
  - pip=25.2
  - pip:
    - control==0.10.2
    - spyder==6.0.8
    - seaborn==0.13.2
    - numpy==2.3.3
    - scipy==1.16.2
    - notebook==7.6.2